# Generated by Django 3.2.3 on 2021-06-02 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField(blank=True)),
                ('checked_off', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['checked_off', 'name'],
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('budget', models.IntegerField(default=0)),
                ('items', models.ManyToManyField(to='shopping_list.Item')),
            ],
            options={
                'ordering': ['-updated_on'],
            },
        ),
    ]
