# Generated by Django 3.2.3 on 2021-06-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0002_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
