# Generated by Django 3.2.7 on 2021-09-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0003_alter_list_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created on'),
        ),
    ]
