# Generated by Django 3.2.7 on 2021-09-22 21:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopping_list', '0004_alter_list_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='shoppinglist', to=settings.AUTH_USER_MODEL),
        ),
    ]
