# Generated by Django 3.2.7 on 2021-10-16 21:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopping_list', '0007_friendrequest_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='shared_friends',
            field=models.ManyToManyField(blank=True, related_name='sharedfriends', to=settings.AUTH_USER_MODEL),
        ),
    ]
