# Generated by Django 3.2.7 on 2021-10-18 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0008_list_shared_friends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='shared_friends',
            new_name='shared_with',
        ),
    ]
